### ISSUE TITLE
Errors while building the project

### ISSUE THREAD

**Issue by runofthemillgeek** [alanconway/envoy-amqp#3]
Hey Alan!

I'm unable to build this project. I am trying to use `envoyproxy/envoy-build` to build this project.

First issue is that the submodules you're added aren't working. The `proton`'s repo URL has changed and the `envoy` commit doesn't exist anymore. I've managed to change these to the correct paths but can't figure out which envoy build you're using.

I've then installed the dependencies required to install proton and managed to build proton successfully.

When I try to `bazel build` in the end, I'm getting errors for some of the `load(...)` statements. This is the error:

```
INFO: Invocation ID: 80936383-2acb-4d34-8a3f-608b8b47305e
ERROR: error loading package '': Unable to load file '@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl': file doesn't exist
INFO: Elapsed time: 0.194s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I'm not very familiar with `bazel` to understand what exactly is going wrong here but I'm guessing these references on `load` to remote repos are changed or missing. Could you update the instructions on how to build this and maybe update the dependencies? TIA.

**Comment by alanconway** [comment]
Should be fixed by recent commits on master up to eb0e7ca
